# Generated by Django 4.2.27 on 2025-12-16 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TourPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('Family', 'Family'), ('Adventure', 'Adventure'), ('Luxury', 'Luxury'), ('Budget', 'Budget'), ('Friends', 'Friends'), ('Wildlife', 'Wildlife')], max_length=20)),
                ('description', models.TextField()),
                ('duration', models.CharField(max_length=50)),
                ('people', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(upload_to='packages/')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
